apiVersion: v1
kind: ServiceAccount
metadata:
  name: created-from-universe
  namespace: org-a
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: org-a:created-from-universe:edit
  namespace: org-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: created-from-universe
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: created-from-universe
  namespace: org-b
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: org-b:created-from-universe:edit
  namespace: org-b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: created-from-universe
