apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kyverno
spec:
  sourceRef:
    kind: GitRepository
    name: pawel-flux-poc
  path: ./webhook/kyverno
  prune: true
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno
      namespace: kyverno
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kyverno-policies
  namespace: flux-system
spec:
  dependsOn:
    - name: kyverno
  sourceRef:
    kind: GitRepository
    name: pawel-flux-poc
  path: ./webhook/kyverno-policies
  prune: true
  validation: client
